travis:
  secure:
    BINSTAR_TOKEN: h0eI0Zcxrs2C4i5WR6iyu9U+n8xripqjkmvCMVKBHBPIwrYcpRdXjwCWzMXsa1hMNAXHjIebb+cbmNyTl1yHkAFITN1R2AN49BxGuTIlZhYwpi+ZJVW3DQi1t/HJkHV1buuG4xwQ668w34spif7BhmjR8DgB/vZphLQDNG7e6PqYt4VbRPEQ0xMXM9OdXhCcjWq5IP4iGccVu5R80xFIlEP9fGQdg4AkLPC3ooAgCVtWW8MepdW5p2SiiDGktyahBaL4Nqlfd8KyDP6bHfew4vM6RxpsXoza3K6MR4vrbcntB5n+NSoH+LUf9rQEYSz9orjUU0uZyBnTrZlTddPYc1CIWOP7GW1QSA6PEnjzTemqkj5RIsrasDVynIMrokXBcsCGgjqwWoRhQyMKkIIp3xYK9m6PLQhUsATl197Nk3cmjAV/nRtNWpNudPALXd5rTNK+V3KYiVyyCusQvthiob54hfWBff8tZmlk/gD4oZwHCpAYPM5EsiW9AIytj2ci3hW4tOYDjV1PeWSz3VUQN14vNkAORmr9pmEMIQ/eyGHlcxfKQCDQyu9wYsblnZKBdKWKx9EuJLO7VbIwLgIO5MmfdVQ1lYjLsLIGqTyKWY0lRECP2Z25sR9wOoLQ6MV4rV3QOhL+oID2y/YALwF0MVZ56+VF67sHvO77vusq6P0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
