travis:
  secure:
    BINSTAR_TOKEN: TzEfROlFicbH9gC5y2GGhO8ySDCvl2lD+bcyf1RnkKIMUYkckC7pYklX+oKxAHzkpICi9mtIcQaEFcWKgOuk5EaxIFyTkxcqpEEsCBPo4UNmtWGYuFWjZBrN5xwAiQ/6EaCOEAuyboAD/cwE2Km6IJZ1O2i2++UWnevtLzyp3tpEDcYidaG8XfiWUEprxQD2ZnOakUcVXMos6bhhz1BIFBmbTB1eqNFGsQtYE3e/uwpHeX0Freu3glHDav4Ti/eSabprsxkOlRG/pJ276C7tba+e2RlODEFWBG2g1wpRLxjA1agE9OWB+AAMW+BGp3JmQEG61H861O/GHUzbbYF60pe/0Sm+UMvo0zKF8+n617t4kTxuXS3bsDFw8en5f2Q1Z0tZH1GK0Rm9g0KchuGkQPOHIxtwt2NyRUJ+PWyj7Iw0+fRlEelci00hpAJ4DyltHMeyf7EcWs4C0IsJj5MzPFcdLhCcibdGXmXCPug/gtfyLYqghMKuIHI0UdCY8S8BhgprW0LE+bUCaFod7uHs9V5AU1/hCuD9NoeF3CHIzcZ1UbqmzRAwqy664F1NYqIDMSvgK3Ub9bnaQSblzW0lT1CnCJyXuiZVIkJ+yPpc7G1fs5R6sQVTM7z4Ic0QyWyGrohV5dIsqhNuOuMZJytz3s4sWw766e36sfU+AtkFLvA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
